### ISSUE TITLE
Difficulty with first installation

### ISSUE THREAD

**Issue by minhlab** [hltcoe/concrete-java#8]
I'm trying to start with Concrete, first by parsing the Gigaword corpus. The script `ingest-gw.sh` gives me this error: 

```
[minhle@fs0 gigaword]$ ./ingest-gw.sh /home/minhle/scratch/gigaword ../../output/gigaword
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: edu/jhu/hlt/utilt/io/NotFileException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: edu.jhu.hlt.utilt.io.NotFileException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

This is what I have done so far:

```
git clone https://github.com/hltcoe/concrete-java.git
rm -rf concrete-java/.git
cd concrete-java
mvn clean package
cd ingesters/gigaword
./ingest-gw.sh /home/minhle/scratch/gigaword ../../output/gigaword
```

BTW, following the instruction in `ingesters/gigaword` folder gives me this error:

```
mvn clean compile assembly:single
...
[ERROR] Failed to execute goal on project concrete-ingesters-gigaword: Could not resolve dependencies for project edu.jhu.hlt:concrete-ingesters-gigaword:jar:4.12.1-SNAPSHOT: The following artifacts could not be resolved: edu.jhu.hlt:concrete-util:jar:4.12.1-SNAPSHOT, edu.jhu.hlt:concrete-validation:jar:4.12.1-SNAPSHOT, edu.jhu.hlt:concrete-ingesters-base:jar:4.12.1-SNAPSHOT: Failure to find edu.jhu.hlt:concrete-util:jar:4.12.1-SNAPSHOT in https://clojars.org/repo was cached in the local repository, resolution will not be reattempted until the update interval of clojars has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by twolfe18** [comment]
I believe you have to run `mvn clean compile install` from the project root (concrete-java/ not concrete-java/ingesters/gigaword) before following the instructions in the [readme](https://github.com/hltcoe/concrete-java/tree/master/ingesters/gigaword).

You can also add `-DskipTests` if that command is slow. Ping back if that doesn't fix the problem.

**Comment by twolfe18** [comment]
Well, now that I've tried my own suggestion, it doesn't seem to work. There is an error while compiling the MisCommunication module which I'm not familiar with. Will look into.

**Comment by twolfe18** [comment]
Oh, right, MisCommunication uses some compiler plugin which is jenky and fails if you do `compile install`; `install` already forces a `compile` and when two compiles happen that compiler plugin dies.

Just run `mvn clean install` from the project root. From there you will have all the SNAPSHOT dependencies and can build a JAR in the fashion described in the readme.

**Comment by minhlab** [comment]
Thanks, it works now. I submitted a PR so that people won't have this problem again.
